language: r
cache: packages
warnings_are_errors: false

r:
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    
    